services:
  roman-numerals:
    container_name: decimal-to-roman-numerals
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: ./bin/main

  prometheus:
    image: prom/prometheus:v2.45.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:10.2.4
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./config/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./config/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  grafana:
