// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Asutosh",
            "email": "asutosh.satapathy@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "ping example",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/GetRoman": {
            "get": {
                "description": "Get the roman numeral equivalent for a given decimal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "romans"
                ],
                "summary": "Get Roman Numeral",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved a Roman",
                        "schema": {
                            "$ref": "#/definitions/models.Roman"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Roman": {
            "type": "object",
            "properties": {
                "decimal": {
                    "type": "integer"
                },
                "roman": {
                    "type": "string"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Roman Numeral Convertor API",
	Description:      "This API takes a range of decimals and converts it to roman numerals",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
