// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Asutosh",
            "email": "asutosh.satapathy@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/convert": {
            "get": {
                "description": "Get the roman numeral equivalent for a given decimal(s) in ascending order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "romans"
                ],
                "summary": "Get Roman Numeral",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved Roman Numerals",
                        "schema": {
                            "$ref": "#/definitions/models.RomanNumeral"
                        }
                    }
                }
            },
            "post": {
                "description": "Get the roman numeral equivalent for given ranges in ascending order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "romans"
                ],
                "summary": "Get Roman Numerals for Ranges of Numbers",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved Roman Numerals",
                        "schema": {
                            "$ref": "#/definitions/models.RomanNumeral"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.RomanNumeral": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "integer"
                },
                "roman": {
                    "type": "string"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Roman Numeral Convertor API",
	Description:      "This API takes a range of decimals and converts it to roman numerals",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
