// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Asutosh",
            "email": "asutosh.satapathy@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/convert": {
            "get": {
                "description": "Convert a comma-separated list of numbers to their corresponding Roman numeral representations.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Convert numbers to Roman numerals",
                "operationId": "convertNumbersToRoman",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated list of integers to be converted",
                        "name": "numbers",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RomanNumeral"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Convert multiple ranges of numbers to their corresponding Roman numeral representations.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Convert ranges of numbers to Roman numerals",
                "operationId": "convertRangesToRoman",
                "parameters": [
                    {
                        "description": "Array of number ranges",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RangesPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RomanNumeral"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.NumberRange": {
            "type": "object",
            "required": [
                "max",
                "min"
            ],
            "properties": {
                "max": {
                    "description": "The maximum value of the range (inclusive).",
                    "type": "integer",
                    "example": 20
                },
                "min": {
                    "description": "The minimum value of the range (inclusive).",
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "models.RangesPayload": {
            "type": "object",
            "required": [
                "ranges"
            ],
            "properties": {
                "ranges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NumberRange"
                    }
                }
            }
        },
        "models.RomanNumeral": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "integer"
                },
                "roman": {
                    "type": "string"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Roman Numeral Converter API",
	Description:      "This API takes a range of decimals and converts it to roman numerals",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
