basePath: /
definitions:
  models.RomanNumeral:
    properties:
      number:
        type: integer
      roman:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8001
info:
  contact:
    email: asutosh.satapathy@gmail.com
    name: Asutosh
  description: This API takes a range of decimals and converts it to roman numerals
  title: Roman Numeral Convertor API
  version: "1.0"
paths:
  /convert:
    get:
      description: Get the roman numeral equivalent for a given decimal(s) in ascending
        order
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved Roman Numerals
          schema:
            $ref: '#/definitions/models.RomanNumeral'
      summary: Get Roman Numeral
      tags:
      - romans
  /ranges:
    get:
      description: Get the roman numeral equivalent for given ranges in ascending
        order
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved Roman Numerals
          schema:
            $ref: '#/definitions/models.RomanNumeral'
      summary: Get Roman Numerals for Ranges of Numbers
      tags:
      - romans
swagger: "2.0"
