basePath: /api/v1
definitions:
  models.NumberRange:
    properties:
      max:
        description: The maximum value of the range (inclusive).
        example: 20
        type: integer
      min:
        description: The minimum value of the range (inclusive).
        example: 10
        type: integer
    required:
    - max
    - min
    type: object
  models.RangesPayload:
    properties:
      ranges:
        items:
          $ref: '#/definitions/models.NumberRange'
        type: array
    required:
    - ranges
    type: object
  models.RomanNumeral:
    properties:
      number:
        type: integer
      roman:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8001
info:
  contact:
    email: asutosh.satapathy@gmail.com
    name: Asutosh
  description: This API takes a range of decimals and converts it to roman numerals
  title: Roman Numeral Converter API
  version: "1.0"
paths:
  /convert:
    get:
      consumes:
      - application/json
      description: Convert a comma-separated list of numbers to their corresponding
        Roman numeral representations.
      operationId: convertNumbersToRoman
      parameters:
      - description: Comma-separated list of integers to be converted
        in: query
        name: numbers
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.RomanNumeral'
            type: array
      summary: Convert numbers to Roman numerals
    post:
      consumes:
      - application/json
      description: Convert multiple ranges of numbers to their corresponding Roman
        numeral representations.
      operationId: convertRangesToRoman
      parameters:
      - description: Array of number ranges
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.RangesPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.RomanNumeral'
            type: array
      summary: Convert ranges of numbers to Roman numerals
swagger: "2.0"
